// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpf1-KqlZNitegIJWipmV6sXb6nCfkbDk',
    appId: '1:165105899359:web:90138ec2b483b57724c8ea',
    messagingSenderId: '165105899359',
    projectId: 'hemendradevatwal-1d97b',
    authDomain: 'hemendradevatwal-1d97b.firebaseapp.com',
    storageBucket: 'hemendradevatwal-1d97b.firebasestorage.app',
    measurementId: 'G-8PNKEHG2C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA3IfEUIjSakJrWuN9M3pCrumN2DIpxTc',
    appId: '1:165105899359:android:e27c640aa72ec75324c8ea',
    messagingSenderId: '165105899359',
    projectId: 'hemendradevatwal-1d97b',
    storageBucket: 'hemendradevatwal-1d97b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxHE_E4hKuU_ny1pYwTfqrzO_4rxxTZSE',
    appId: '1:165105899359:ios:8b9a5abf8d11542b24c8ea',
    messagingSenderId: '165105899359',
    projectId: 'hemendradevatwal-1d97b',
    storageBucket: 'hemendradevatwal-1d97b.firebasestorage.app',
    iosBundleId: 'com.hemendradev.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxHE_E4hKuU_ny1pYwTfqrzO_4rxxTZSE',
    appId: '1:165105899359:ios:8b9a5abf8d11542b24c8ea',
    messagingSenderId: '165105899359',
    projectId: 'hemendradevatwal-1d97b',
    storageBucket: 'hemendradevatwal-1d97b.firebasestorage.app',
    iosBundleId: 'com.hemendradev.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpf1-KqlZNitegIJWipmV6sXb6nCfkbDk',
    appId: '1:165105899359:web:8ac0f8205d8605a624c8ea',
    messagingSenderId: '165105899359',
    projectId: 'hemendradevatwal-1d97b',
    authDomain: 'hemendradevatwal-1d97b.firebaseapp.com',
    storageBucket: 'hemendradevatwal-1d97b.firebasestorage.app',
    measurementId: 'G-CVCGGF8VNX',
  );

}